---
- name: Install redis
  apt: name=redis-server state=latest

- name: Download deb package for erlang repo
  get_url: 
    dest=/tmp
    url=http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    mode=755
  
- name: Install deb package for erlang repo
  apt: deb=/tmp/erlang-solutions_1.0_all.deb

- name: Download key for erlang repo
  apt_key: url=http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc state=present

- name: Install erlang
  apt: name=erlang-nox state=latest update_cache=yes

- name: Install NTP
  apt: name=ntp state=latest

- name: Start NTP on boot
  service: name=ntp state=started enabled=yes

- name: Install python-apt
  apt: name=python-apt state=latest

- name: Install RabbitMQ repository
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Install RabbitMQ signing key
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: Install RabbitMQ 
  apt: name=rabbitmq-server state=latest force=yes

- name: Copy over SSL certificates (do not check into repo)
  copy: src={{ item }} dest=/etc/rabbitmq/ssl/
  with_items:
    - cacert.pem
    - cert.pem
    - key.pem
  notify: restart rabbitmq 

- name: Configure SSL via template
  template: src=rabbitmq.config.j2  dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbitmq

- name: Enable management console
  command: rabbitmq-plugins enable rabbitmq_management
  notify: restart rabbitmq 

- name: Start RabbitMQ on boot
  service: name=rabbitmq-server state=started enabled=yes

- name: Create RabbitMQ vhost 
  command: rabbitmqctl add_vhost /sensu
  ignore_errors: yes 

- name: Add user for sensu 
  command: rabbitmqctl add_user sensu {{ rabbit_password }} 
  ignore_errors: yes 

- name: Add sensu user to web interface
  command: rabbitmqctl set_user_tags sensu administrator
  ignore_errors: yes 

- name: Set permissions
  command: rabbitmqctl set_permissions -p /sensu sensu ".*" ".*" ".*"  
  ignore_errors: yes 
